(function(){
  'use strict';
  var button=document.getElementById('knowledgeUploadButton'),input=document.getElementById('knowledgeUploadInput'),list=document.getElementById('serverKnowledgeList'),count=document.getElementById('knowledgeServerCount'),status=document.getElementById('knowledgeServerStatus'),badge=document.getElementById('knowledgeServerBadge');
  if(!button||!input||!list)return;
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]})}
  function message(title,detail,error){status.querySelector('strong').textContent=title;status.querySelector('span:not(.notice-icon)').textContent=detail||'';status.classList.toggle('moodle-config-error',!!error)}
  function request(action,options){var config=options||{},url='api/knowledge.php?action='+encodeURIComponent(action);return fetch(url,config).then(function(response){return response.text().then(function(raw){var data={};try{data=raw?JSON.parse(raw):{}}catch(ignore){}if(!response.ok||data.ok===false)throw new Error(data.error||'Không thể kết nối kho dữ liệu AI.');return data})})}
  function render(data){var items=data.sources||[];count.textContent=(data.active_source_count||0)+' đang dùng · '+items.length+' tổng';badge.textContent='● '+(data.chunk_count||0)+' đoạn kiến thức';list.innerHTML=items.length?items.map(function(item){return '<div class="source-item"><span class="source-type">'+(item.active?'✦':'○')+'</span><span style="min-width:0;flex:1"><h4>'+esc(item.title)+'</h4><p>'+esc(item.type)+' · '+esc(item.year||'Chưa rõ năm')+' · '+esc(item.origin==='upload'?'Đã tải lên':'Dữ liệu ban đầu')+(item.warning?' · '+esc(item.warning):'')+'</p></span><label class="check-row" style="white-space:nowrap"><input type="checkbox" data-knowledge-toggle="'+esc(item.id)+'" '+(item.active?'checked':'')+'> Dùng cho AI</label></div>'}).join(''):'<div class="empty">Chưa có nguồn kiến thức trên máy chủ.</div>'}
  function load(){request('list').then(function(data){render(data);message('Kho dữ liệu AI đã kết nối',(data.active_source_count||0)+' nguồn đang được chatbot sử dụng.',false)}).catch(function(error){message('Chưa kết nối được kho dữ liệu AI',error.message,true);list.innerHTML='<div class="empty">'+esc(error.message)+'</div>';count.textContent='Không tải được'})}
  button.onclick=function(){input.click()};
  input.onchange=function(){var files=Array.prototype.slice.call(input.files||[]);if(!files.length)return;button.disabled=true;var done=0;message('Đang đọc '+files.length+' tài liệu','Không đóng trang trong lúc xử lý PDF hoặc ảnh.',false);files.reduce(function(chain,file){return chain.then(function(){var body=new FormData();body.append('file',file);body.append('type','Tuyển sinh');return request('upload',{method:'POST',body:body}).then(function(){done++;message('Đã xử lý '+done+'/'+files.length,file.name,false)})})},Promise.resolve()).then(function(){input.value='';button.disabled=false;load()}).catch(function(error){input.value='';button.disabled=false;message('Không nhập được tài liệu',error.message,true);load()})};
  list.addEventListener('change',function(event){var checkbox=event.target.closest('[data-knowledge-toggle]');if(!checkbox)return;checkbox.disabled=true;request('toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:checkbox.getAttribute('data-knowledge-toggle'),active:checkbox.checked})}).then(load).catch(function(error){checkbox.checked=!checkbox.checked;checkbox.disabled=false;message('Không đổi được trạng thái',error.message,true)})});
  load();
})();
