<?php
/* Import student profiles from CSV/XLSX and attach private photos/documents. PHP 5.6 compatible. */
header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store');
function mtpc_students_response($status,$payload){http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
require __DIR__.'/_student_bootstrap.php';

function import_text($value,$limit){$value=trim((string)$value);return function_exists('mb_substr')?mb_substr($value,0,$limit,'UTF-8'):substr($value,0,$limit);}
function import_header_key($value){$value=trim(strtolower((string)$value));if(function_exists('iconv')){$ascii=@iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value);if($ascii!==false)$value=$ascii;}$value=preg_replace('/[^a-z0-9]+/','_',$value);return trim($value,'_');}
function import_aliases(){return array(
 'student_code'=>array('student_code','ma_sinh_vien','ma_sv','masv'),
 'full_name'=>array('full_name','ho_va_ten','ho_ten','ten_sinh_vien'),
 'date_of_birth'=>array('date_of_birth','ngay_sinh'),
 'gender'=>array('gender','gioi_tinh'),
 'citizen_id'=>array('citizen_id','cccd','cmnd','so_cccd'),
 'phone'=>array('phone','dien_thoai','so_dien_thoai','sdt'),
 'email'=>array('email','thu_dien_tu'),
 'address'=>array('address','dia_chi'),
 'guardian_name'=>array('guardian_name','nguoi_lien_he','phu_huynh','ho_ten_phu_huynh'),
 'guardian_phone'=>array('guardian_phone','sdt_nguoi_lien_he','sdt_phu_huynh'),
 'program_name'=>array('program_name','nganh','nganh_hoc'),
 'class_name'=>array('class_name','lop','lop_hoc'),
 'admission_year'=>array('admission_year','nam_nhap_hoc'),
 'cohort'=>array('cohort','khoa','khoa_hoc'),
 'status'=>array('status','trang_thai'),
 'note'=>array('note','ghi_chu')
 );}
function import_map_headers($headers){$aliases=import_aliases();$map=array();foreach($headers as$i=>$header){$key=import_header_key($header);foreach($aliases as$field=>$options)if(in_array($key,$options,true)){$map[$i]=$field;break;}}return $map;}
function import_normalize_date($value){$value=trim((string)$value);if($value==='')return null;if(is_numeric($value)&&$value>20000){$time=((int)$value-25569)*86400;return gmdate('Y-m-d',$time);}foreach(array('Y-m-d','d/m/Y','d-m-Y','m/d/Y')as$format){$date=DateTime::createFromFormat($format,$value);if($date&&$date->format($format)===$value)return$date->format('Y-m-d');}return$value;}
function import_row_from_cells($cells,$map){$row=array();foreach($map as$i=>$field)$row[$field]=isset($cells[$i])?trim((string)$cells[$i]):'';return$row;}
function import_parse_csv($path){$sample=file_get_contents($path,false,null,0,4096);$counts=array(','=>substr_count($sample,','),';'=>substr_count($sample,';'),"\t"=>substr_count($sample,"\t"));arsort($counts);$delimiter=key($counts);$handle=fopen($path,'r');if(!$handle)throw new Exception('Không đọc được file CSV.');$headers=fgetcsv($handle,0,$delimiter);if(!$headers){fclose($handle);return array();}$headers[0]=preg_replace('/^\xEF\xBB\xBF/','',$headers[0]);$map=import_map_headers($headers);$rows=array();while(($cells=fgetcsv($handle,0,$delimiter))!==false){$has=false;foreach($cells as$cell)if(trim((string)$cell)!==''){$has=true;break;}if($has)$rows[]=import_row_from_cells($cells,$map);}fclose($handle);return$rows;}
function import_xlsx_cell_value($cell,$shared){$type=(string)$cell['t'];if($type==='inlineStr')return isset($cell->is->t)?(string)$cell->is->t:'';$value=isset($cell->v)?(string)$cell->v:'';if($type==='s'&&isset($shared[(int)$value]))return$shared[(int)$value];if($type==='b')return$value==='1'?'1':'0';return$value;}
function import_parse_xlsx($path){if(!class_exists('ZipArchive'))throw new Exception('Hosting chưa bật ZipArchive. Hãy lưu Excel thành CSV UTF-8 rồi nhập lại.');$zip=new ZipArchive();if($zip->open($path)!==true)throw new Exception('Không mở được file XLSX.');$shared=array();$raw=$zip->getFromName('xl/sharedStrings.xml');if($raw!==false){$xml=@simplexml_load_string($raw);if($xml)foreach($xml->si as$si){$text='';if(isset($si->t))$text=(string)$si->t;else foreach($si->r as$r)$text.=(string)$r->t;$shared[]=$text;}}$sheet=$zip->getFromName('xl/worksheets/sheet1.xml');$zip->close();if($sheet===false)throw new Exception('Không tìm thấy sheet đầu tiên trong file XLSX.');$xml=@simplexml_load_string($sheet);if(!$xml)throw new Exception('File XLSX không hợp lệ.');$matrix=array();foreach($xml->sheetData->row as$row){$cells=array();foreach($row->c as$cell){$ref=(string)$cell['r'];preg_match('/^[A-Z]+/',$ref,$match);$letters=isset($match[0])?$match[0]:'A';$index=0;for($i=0;$i<strlen($letters);$i++)$index=$index*26+(ord($letters[$i])-64);$cells[$index-1]=import_xlsx_cell_value($cell,$shared);}if(count($cells)){$max=max(array_keys($cells));$line=array();for($i=0;$i<=$max;$i++)$line[]=isset($cells[$i])?$cells[$i]:'';$matrix[]=$line;}}if(!count($matrix))return array();$headers=array_shift($matrix);$map=import_map_headers($headers);$rows=array();foreach($matrix as$cells)$rows[]=import_row_from_cells($cells,$map);return$rows;}
function import_parse_sheet($file){if(!isset($file['tmp_name'])||!is_uploaded_file($file['tmp_name']))throw new Exception('Bạn chưa chọn file Excel hoặc CSV.');$ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));if($ext==='csv')return import_parse_csv($file['tmp_name']);if($ext==='xlsx')return import_parse_xlsx($file['tmp_name']);throw new Exception('Chỉ hỗ trợ .xlsx hoặc .csv UTF-8.');}
function import_clean_row($row){$year=isset($row['admission_year'])?(int)$row['admission_year']:0;$email=import_text(isset($row['email'])?$row['email']:'',150);return array(
 'student_code'=>import_text(isset($row['student_code'])?$row['student_code']:'',30),'full_name'=>import_text(isset($row['full_name'])?$row['full_name']:'',150),'date_of_birth'=>import_normalize_date(isset($row['date_of_birth'])?$row['date_of_birth']:''),'gender'=>import_text(isset($row['gender'])?$row['gender']:'',20),'citizen_id'=>import_text(isset($row['citizen_id'])?$row['citizen_id']:'',20),'phone'=>import_text(isset($row['phone'])?$row['phone']:'',30),'email'=>$email,'address'=>import_text(isset($row['address'])?$row['address']:'',500),'guardian_name'=>import_text(isset($row['guardian_name'])?$row['guardian_name']:'',150),'guardian_phone'=>import_text(isset($row['guardian_phone'])?$row['guardian_phone']:'',30),'program_name'=>import_text(isset($row['program_name'])?$row['program_name']:'',150),'class_name'=>import_text(isset($row['class_name'])?$row['class_name']:'',100),'admission_year'=>$year>=2000&&$year<=2100?$year:null,'cohort'=>import_text(isset($row['cohort'])?$row['cohort']:'',50),'status'=>import_text(isset($row['status'])?$row['status']:'Đang học',50),'note'=>import_text(isset($row['note'])?$row['note']:'',2000));}
function import_validate_rows($pdo,$raw){$rows=array();$errors=array();$warnings=array();$seen=array('student_code'=>array(),'citizen_id'=>array(),'email'=>array(),'phone'=>array());$unique=array('citizen_id'=>'CCCD','email'=>'email','phone'=>'số điện thoại');$checks=array();foreach($unique as$field=>$label)$checks[$field]=$pdo->prepare('SELECT student_code FROM students WHERE '.$field.'=:value AND student_code<>:code LIMIT 1');foreach($raw as$i=>$source){$row=import_clean_row($source);$line=$i+2;if($row['student_code']===''||$row['full_name']===''){$errors[]=array('row'=>$line,'student_code'=>$row['student_code'],'error'=>'Thiếu mã sinh viên hoặc họ tên.');continue;}if($row['email']!==''&&!filter_var($row['email'],FILTER_VALIDATE_EMAIL)){$errors[]=array('row'=>$line,'student_code'=>$row['student_code'],'error'=>'Email không hợp lệ.');continue;}if($row['date_of_birth']!==null&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$row['date_of_birth'])){$errors[]=array('row'=>$line,'student_code'=>$row['student_code'],'error'=>'Ngày sinh phải có dạng YYYY-MM-DD hoặc DD/MM/YYYY.');continue;}foreach($seen as$field=>$unused){$value=strtolower((string)$row[$field]);if($value==='')continue;if(isset($seen[$field][$value])){$errors[]=array('row'=>$line,'student_code'=>$row['student_code'],'error'=>'Trùng '.$field.' với dòng '.$seen[$field][$value].' trong file.');continue 2;}$seen[$field][$value]=$line;}foreach($unique as$field=>$label){if($row[$field]==='')continue;$checks[$field]->execute(array(':value'=>$row[$field],':code'=>$row['student_code']));$other=$checks[$field]->fetchColumn();if($other){$errors[]=array('row'=>$line,'student_code'=>$row['student_code'],'error'=>ucfirst($label).' đã thuộc hồ sơ '.$other.'.');continue 2;}}$rows[]=$row;}$codes=array();foreach($rows as$row)$codes[]=$row['student_code'];if(count($codes)){$marks=implode(',',array_fill(0,count($codes),'?'));$st=$pdo->prepare('SELECT student_code FROM students WHERE student_code IN ('.$marks.')');$st->execute($codes);foreach($st->fetchAll()as$existing)$warnings[]=array('student_code'=>$existing['student_code'],'warning'=>'Hồ sơ đã có và sẽ được cập nhật.');}return array($rows,$errors,$warnings);}
function import_image_code($name){$base=pathinfo(basename($name),PATHINFO_FILENAME);$base=preg_replace('/(?:[_-](?:anh|photo|avatar|hoso|giayto|document))$/i','',$base);return trim($base);}
function import_resolve_code($name,$codes){$base=strtolower(import_image_code($name));if(isset($codes[$base]))return$codes[$base];$best=null;$length=0;foreach($codes as$key=>$value)if((strpos($base,$key.'_')===0||strpos($base,$key.'-')===0)&&strlen($key)>$length){$best=$value;$length=strlen($key);}return$best;}
function import_uploaded_images(){ $items=array();if(isset($_FILES['images'])&&is_array($_FILES['images']['name']))for($i=0;$i<count($_FILES['images']['name']);$i++)if($_FILES['images']['error'][$i]===UPLOAD_ERR_OK)$items[]=array('name'=>$_FILES['images']['name'][$i],'tmp'=>$_FILES['images']['tmp_name'][$i],'data'=>null);if(isset($_FILES['image_archive'])&&$_FILES['image_archive']['error']===UPLOAD_ERR_OK){if(!class_exists('ZipArchive'))throw new Exception('Hosting chưa bật ZipArchive nên không đọc được ZIP. Bạn có thể chọn nhiều ảnh trực tiếp.');$zip=new ZipArchive();if($zip->open($_FILES['image_archive']['tmp_name'])!==true)throw new Exception('Không mở được file ZIP ảnh.');if($zip->numFiles>1000){$zip->close();throw new Exception('ZIP vượt quá 1.000 tệp.');}for($i=0;$i<$zip->numFiles;$i++){$stat=$zip->statIndex($i);$name=basename($stat['name']);$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if($name!==''&&in_array($ext,array('jpg','jpeg','png','webp'),true))$items[]=array('name'=>$name,'tmp'=>null,'data'=>$zip->getFromIndex($i));}$zip->close();}return$items;}
function import_image_mime($item){$info=$item['tmp']?@getimagesize($item['tmp']):@getimagesizefromstring($item['data']);if(!$info||!isset($info['mime']))return null;$map=array('image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp');return isset($map[$info['mime']])?array($info['mime'],$map[$info['mime']]):null;}
function import_image_preview($pdo,$items,$rows){$matched=0;$unmatched=array();$invalid=array();$codes=array();foreach($pdo->query('SELECT student_code FROM students')as$student)$codes[strtolower($student['student_code'])]=$student['student_code'];foreach($rows as$row)$codes[strtolower($row['student_code'])]=$row['student_code'];foreach($items as$item){$mime=import_image_mime($item);if(!$mime){$invalid[]=$item['name'];continue;}if(import_resolve_code($item['name'],$codes)!==null)$matched++;else$unmatched[]=$item['name'];}return array('total'=>count($items),'matched'=>$matched,'unmatched'=>$unmatched,'invalid'=>$invalid);}
function import_ensure_dir($path){if(!is_dir($path)&&!mkdir($path,0700,true))throw new Exception('Không tạo được thư mục lưu ảnh private.');@chmod($path,0700);}
function import_save_images($pdo,$items,$kind,$actor){$root='/home/mtpc/private/student-files';import_ensure_dir($root);import_ensure_dir($root.'/photos');import_ensure_dir($root.'/documents');$matched=0;$unmatched=array();$invalid=array();$codes=array();foreach($pdo->query('SELECT id,student_code,photo_path FROM students')as$student)$codes[strtolower($student['student_code'])]=$student;foreach($items as$item){$mime=import_image_mime($item);if(!$mime){$invalid[]=$item['name'];continue;}$student=import_resolve_code($item['name'],$codes);if(!$student){$unmatched[]=$item['name'];continue;}$bytes=$item['tmp']?file_get_contents($item['tmp']):$item['data'];if($bytes===false||strlen($bytes)>8*1024*1024){$invalid[]=$item['name'];continue;}$ext=$mime[1];if($kind==='document'){$dir=$root.'/documents/'.(int)$student['id'];import_ensure_dir($dir);$relative='documents/'.(int)$student['id'].'/'.date('YmdHis').'-'.substr(md5($item['name'].uniqid('',true)),0,10).'.'.$ext;$path=$root.'/'.$relative;if(file_put_contents($path,$bytes)===false){$invalid[]=$item['name'];continue;}@chmod($path,0600);$q=$pdo->prepare('INSERT INTO student_documents(student_id,document_type,file_name,file_path,status,note,uploaded_by) VALUES(:student,"Hồ sơ nhập hàng loạt",:name,:path,"pending","Nhập cùng Excel",:actor)');$q->execute(array(':student'=>$student['id'],':name'=>basename($item['name']),':path'=>$relative,':actor'=>$actor));}else{$relative='photos/'.(int)$student['id'].'.'.$ext;$path=$root.'/'.$relative;if(file_put_contents($path,$bytes)===false){$invalid[]=$item['name'];continue;}@chmod($path,0600);if(!empty($student['photo_path'])&&$student['photo_path']!==$relative&&strpos($student['photo_path'],'photos/')===0){$old=realpath($root.'/'.$student['photo_path']);$safeRoot=realpath($root);if($old&&$safeRoot&&strpos($old,$safeRoot.DIRECTORY_SEPARATOR)===0&&is_file($old))@unlink($old);}$q=$pdo->prepare('UPDATE students SET photo_path=:path WHERE id=:id');$q->execute(array(':path'=>$relative,':id'=>$student['id']));}$matched++;}return array('total'=>count($items),'matched'=>$matched,'unmatched'=>$unmatched,'invalid'=>$invalid);}
function import_commit_rows($pdo,$rows,$actor){$inserted=0;$updated=0;$errors=array();$columns=array('full_name','date_of_birth','gender','citizen_id','phone','email','address','guardian_name','guardian_phone','program_name','class_name','admission_year','cohort','status','note');$find=$pdo->prepare('SELECT id FROM students WHERE student_code=:code LIMIT 1');$pdo->beginTransaction();foreach($rows as$i=>$row){try{$find->execute(array(':code'=>$row['student_code']));$id=$find->fetchColumn();$params=array();foreach($columns as$c)$params[':'.$c]=$row[$c]===''?null:$row[$c];if($id){$params[':id']=$id;$sets=array();foreach($columns as$c)$sets[]=$c.'=COALESCE(:'.$c.','.$c.')';$st=$pdo->prepare('UPDATE students SET '.implode(',',$sets).' WHERE id=:id');$st->execute($params);$updated++;}else{$params[':student_code']=$row['student_code'];$names=array_merge(array('student_code'),$columns);$marks=array();foreach($names as$c)$marks[]=':'.$c;$st=$pdo->prepare('INSERT INTO students('.implode(',',$names).') VALUES('.implode(',',$marks).')');$st->execute($params);$id=$pdo->lastInsertId();$inserted++;}$history=$pdo->prepare('INSERT INTO student_history(student_id,action,new_value,reason,actor_username,actor_role) VALUES(:id,"import",:value,"Nhập Excel/CSV",:actor,:role)');$history->execute(array(':id'=>$id,':value'=>$row['full_name'],':actor'=>$actor['username'],':role'=>$actor['role']));}catch(Exception$e){$errors[]=array('row'=>$i+2,'student_code'=>$row['student_code'],'error'=>'Trùng CCCD, email, số điện thoại hoặc dữ liệu không hợp lệ.');}}$pdo->commit();return array('inserted'=>$inserted,'updated'=>$updated,'errors'=>$errors);}

if($_SERVER['REQUEST_METHOD']==='GET'&&isset($_GET['action'])&&$_GET['action']==='template'){mtpc_require_permission('students.read');header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="mau-import-sinh-vien-mtpc.csv"');echo "\xEF\xBB\xBF";$f=fopen('php://output','w');fputcsv($f,array('student_code','full_name','date_of_birth','gender','citizen_id','phone','email','address','guardian_name','guardian_phone','program_name','class_name','admission_year','cohort','status','note'));fputcsv($f,array('MTPC001','Nguyễn Văn A','2007-05-20','Nam','','','','','','','Công nghệ thông tin','CNTT-K26','2026','K26','Đang học',''));fclose($f);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST')mtpc_students_response(405,array('ok'=>false,'error'=>'Phương thức không được hỗ trợ.'));
mtpc_require_permission('students.write');
try{$raw=import_parse_sheet(isset($_FILES['sheet'])?$_FILES['sheet']:array());if(!count($raw)||count($raw)>1000)throw new Exception('File cần từ 1 đến 1.000 dòng dữ liệu.');list($rows,$errors,$warnings)=import_validate_rows($pdo,$raw);$items=import_uploaded_images();$imagePreview=import_image_preview($pdo,$items,$rows);$mode=isset($_POST['mode'])?$_POST['mode']:'preview';if($mode!=='commit')mtpc_students_response(200,array('ok'=>true,'mode'=>'preview','valid_rows'=>count($rows),'invalid_rows'=>count($errors),'errors'=>array_slice($errors,0,100),'warnings'=>array_slice($warnings,0,100),'sample'=>array_slice($rows,0,8),'images'=>$imagePreview));if(count($errors))throw new Exception('File còn dòng lỗi. Hãy sửa dữ liệu rồi nhập lại.');$result=import_commit_rows($pdo,$rows,$mtpcActor);$kind=isset($_POST['image_kind'])&&$_POST['image_kind']==='document'?'document':'photo';$images=import_save_images($pdo,$items,$kind,$mtpcActor['username']);mtpc_audit('students.bundle_import','student','bulk',null,array('inserted'=>$result['inserted'],'updated'=>$result['updated'],'images'=>$images['matched'],'image_kind'=>$kind));mtpc_students_response(200,array('ok'=>true,'mode'=>'commit','inserted'=>$result['inserted'],'updated'=>$result['updated'],'row_errors'=>$result['errors'],'images'=>$images,'message'=>'Đã nhập dữ liệu sinh viên và đối soát hình ảnh.'));}catch(Exception$e){if($pdo->inTransaction())$pdo->rollBack();mtpc_students_response(422,array('ok'=>false,'error'=>$e->getMessage()));}
