<?php
/* MTPC extended student operations. PHP 5.6 compatible. */
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('Access-Control-Allow-Headers: Content-Type');header('Access-Control-Allow-Methods: GET,POST,OPTIONS');
function mtpc_students_response($status,$payload){http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
require __DIR__.'/_student_bootstrap.php';
function body_json(){$x=json_decode(file_get_contents('php://input'),true);return is_array($x)?$x:array();}
function text_value($v,$n){$v=trim((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n,'UTF-8'):substr($v,0,$n);}
function id_value($v){return max(0,(int)$v);}
$action=isset($_GET['action'])?(string)$_GET['action']:'overview';
try{
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='me')mtpc_students_response(200,array('ok'=>true,'user'=>$mtpcActor,'permissions'=>array('students_read'=>mtpc_has_permission('students.read'),'students_write'=>mtpc_has_permission('students.write'),'attendance_write'=>mtpc_has_permission('attendance.write'),'finance_read'=>mtpc_has_permission('finance.read'),'finance_write'=>mtpc_has_permission('finance.write'))));
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='overview'){
  mtpc_require_permission('students.read');$total=(int)$pdo->query('SELECT COUNT(*) FROM students')->fetchColumn();$today=date('Y-m-d');$s=$pdo->prepare("SELECT COUNT(*) FROM attendance_records r JOIN attendance_sessions s ON s.id=r.session_id WHERE s.session_date=:d AND r.status IN ('absent','late')");$s->execute(array(':d'=>$today));$attendanceWarnings=(int)$s->fetchColumn();$fees=array('due'=>0,'paid'=>0,'debt'=>0);if(mtpc_has_permission('finance.read')){$row=$pdo->query("SELECT COALESCE(SUM(sf.amount_due),0) due,COALESCE(SUM(p.paid),0) paid FROM student_fees sf LEFT JOIN (SELECT student_fee_id,SUM(amount) paid FROM fee_payments GROUP BY student_fee_id)p ON p.student_fee_id=sf.id")->fetch();$fees=array('due'=>(float)$row['due'],'paid'=>(float)$row['paid'],'debt'=>max(0,(float)$row['due']-(float)$row['paid']));}mtpc_students_response(200,array('ok'=>true,'summary'=>array('students'=>$total,'attendance_warnings'=>$attendanceWarnings,'finance'=>$fees)));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='attendance_sessions'){
  mtpc_require_permission('attendance.read');$from=isset($_GET['from'])?text_value($_GET['from'],10):date('Y-m-01');$to=isset($_GET['to'])?text_value($_GET['to'],10):date('Y-m-d');$class=isset($_GET['class_name'])?text_value($_GET['class_name'],100):'';$sql="SELECT s.*,COUNT(r.id) total,SUM(r.status='present') present_count,SUM(r.status='late') late_count,SUM(r.status='excused') excused_count,SUM(r.status='absent') absent_count FROM attendance_sessions s LEFT JOIN attendance_records r ON r.session_id=s.id WHERE s.session_date BETWEEN :f AND :t";$p=array(':f'=>$from,':t'=>$to);if($class!==''){$sql.=' AND s.class_name=:c';$p[':c']=$class;}$sql.=' GROUP BY s.id ORDER BY s.session_date DESC,s.id DESC LIMIT 100';$st=$pdo->prepare($sql);$st->execute($p);mtpc_students_response(200,array('ok'=>true,'sessions'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='attendance_roster'){
  mtpc_require_permission('attendance.read');$id=id_value(isset($_GET['session_id'])?$_GET['session_id']:0);$st=$pdo->prepare('SELECT s.id,s.student_code,s.full_name,s.class_name,COALESCE(r.status,"present") status,r.note FROM attendance_sessions a JOIN students s ON s.class_name=a.class_name LEFT JOIN attendance_records r ON r.session_id=a.id AND r.student_id=s.id WHERE a.id=:id ORDER BY s.full_name');$st->execute(array(':id'=>$id));mtpc_students_response(200,array('ok'=>true,'records'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='attendance_alerts'){
  mtpc_require_permission('attendance.read');$days=isset($_GET['days'])?max(7,min(180,(int)$_GET['days'])):30;$threshold=isset($_GET['threshold'])?max(1,min(30,(int)$_GET['threshold'])):3;$st=$pdo->prepare("SELECT s.id,s.student_code,s.full_name,s.class_name,s.program_name,SUM(r.status='absent') absent_count,SUM(r.status='late') late_count,SUM(r.status='excused') excused_count,ROUND(SUM(r.status='absent')+SUM(r.status='late')*.5,1) warning_score FROM students s JOIN attendance_records r ON r.student_id=s.id JOIN attendance_sessions a ON a.id=r.session_id WHERE a.session_date>=DATE_SUB(CURDATE(),INTERVAL ".$days." DAY) GROUP BY s.id HAVING warning_score>=:threshold ORDER BY warning_score DESC");$st->execute(array(':threshold'=>$threshold));mtpc_students_response(200,array('ok'=>true,'days'=>$days,'threshold'=>$threshold,'alerts'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='fees'){
  mtpc_require_permission('finance.read');$q=isset($_GET['q'])?text_value($_GET['q'],120):'';$status=isset($_GET['status'])?text_value($_GET['status'],20):'';$sql='SELECT sf.id,s.student_code,s.full_name,s.class_name,f.name fee_name,f.due_date,sf.original_amount,sf.discount_amount,sf.amount_due,COALESCE(SUM(p.amount),0) paid_amount,GREATEST(sf.amount_due-COALESCE(SUM(p.amount),0),0) debt_amount,sf.status FROM student_fees sf JOIN students s ON s.id=sf.student_id JOIN fee_items f ON f.id=sf.fee_item_id LEFT JOIN fee_payments p ON p.student_fee_id=sf.id WHERE 1=1';$p=array();if($q!==''){$sql.=' AND (s.student_code LIKE :q OR s.full_name LIKE :q OR s.class_name LIKE :q)';$p[':q']='%'.$q.'%';}if($status!==''){$sql.=' AND sf.status=:status';$p[':status']=$status;}$sql.=' GROUP BY sf.id ORDER BY f.due_date DESC,s.full_name LIMIT 200';$st=$pdo->prepare($sql);$st->execute($p);mtpc_students_response(200,array('ok'=>true,'fees'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='history'){
  mtpc_require_permission('students.read');$id=id_value(isset($_GET['student_id'])?$_GET['student_id']:0);$st=$pdo->prepare('SELECT action,field_name,old_value,new_value,reason,actor_username,actor_role,created_at FROM student_history WHERE student_id=:id ORDER BY id DESC LIMIT 200');$st->execute(array(':id'=>$id));mtpc_students_response(200,array('ok'=>true,'history'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='academic'){
  mtpc_require_permission('academic.read');$id=id_value(isset($_GET['student_id'])?$_GET['student_id']:0);$st=$pdo->prepare('SELECT sem.name semester,sub.code subject_code,sub.name subject,r.process_score,r.exam_score,r.final_score,r.letter_grade,r.result,r.updated_at FROM academic_results r JOIN semesters sem ON sem.id=r.semester_id JOIN subjects sub ON sub.id=r.subject_id WHERE r.student_id=:id ORDER BY sem.start_date DESC,sub.name');$st->execute(array(':id'=>$id));mtpc_students_response(200,array('ok'=>true,'results'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='student_actions'){
  mtpc_require_permission('students.read');$id=id_value(isset($_GET['student_id'])?$_GET['student_id']:0);$st=$pdo->prepare('SELECT id,action_type,decision_no,effective_date,end_date,reason,status,created_by,created_at FROM student_actions WHERE student_id=:id ORDER BY effective_date DESC,id DESC');$st->execute(array(':id'=>$id));mtpc_students_response(200,array('ok'=>true,'actions'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='documents'){
  mtpc_require_permission('students.read');$id=id_value(isset($_GET['student_id'])?$_GET['student_id']:0);$st=$pdo->prepare('SELECT id,document_type,file_name,status,note,uploaded_by,created_at FROM student_documents WHERE student_id=:id ORDER BY id DESC');$st->execute(array(':id'=>$id));mtpc_students_response(200,array('ok'=>true,'documents'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='users'){
  mtpc_require_permission('users.manage');$rows=$pdo->query('SELECT id,username,full_name,role,status,created_at,updated_at FROM admin_users ORDER BY role,full_name')->fetchAll();mtpc_students_response(200,array('ok'=>true,'users'=>$rows));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='audit'){
  mtpc_require_permission('audit.read');$st=$pdo->query('SELECT actor_username,actor_role,action,entity_type,entity_id,ip_address,created_at FROM system_audit_logs ORDER BY id DESC LIMIT 300');mtpc_students_response(200,array('ok'=>true,'audit'=>$st->fetchAll()));
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='export_students'){
  mtpc_require_permission('students.read');$rows=$pdo->query('SELECT student_code,full_name,date_of_birth,gender,citizen_id,phone,email,address,guardian_name,guardian_phone,program_name,class_name,admission_year,cohort,status,note FROM students ORDER BY student_code')->fetchAll();header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="mtpc-students-'.date('Ymd-His').'.csv"');echo "\xEF\xBB\xBF";$f=fopen('php://output','w');fputcsv($f,array('student_code','full_name','date_of_birth','gender','citizen_id','phone','email','address','guardian_name','guardian_phone','program_name','class_name','admission_year','cohort','status','note'));foreach($rows as$row)fputcsv($f,$row);fclose($f);exit;
 }
 if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='backup'){
  mtpc_require_permission('backup.manage');$tables=array('students','student_history','semesters','subjects','academic_results','attendance_sessions','attendance_records','fee_items','student_fees','fee_payments','student_actions');$data=array('version'=>2,'created_at'=>date('c'),'tables'=>array());foreach($tables as$t)$data['tables'][$t]=$pdo->query('SELECT * FROM `'.$t.'`')->fetchAll();header('Content-Disposition: attachment; filename="mtpc-student-backup-'.date('Ymd-His').'.json"');mtpc_students_response(200,$data);
 }
 if($_SERVER['REQUEST_METHOD']!=='POST')mtpc_students_response(405,array('ok'=>false,'error'=>'Phương thức không hỗ trợ.'));
 $b=body_json();
 if($action==='create_attendance_session'){
  mtpc_require_permission('attendance.write');$class=text_value(isset($b['class_name'])?$b['class_name']:'',100);$subject=text_value(isset($b['subject_name'])?$b['subject_name']:'',150);$date=text_value(isset($b['session_date'])?$b['session_date']:'',10);if($class===''||$subject===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))mtpc_students_response(422,array('ok'=>false,'error'=>'Cần lớp, môn và ngày học hợp lệ.'));$st=$pdo->prepare('INSERT INTO attendance_sessions(class_name,subject_name,session_date,period_label,teacher_username,note) VALUES(:c,:s,:d,:p,:u,:n)');$st->execute(array(':c'=>$class,':s'=>$subject,':d'=>$date,':p'=>text_value(isset($b['period_label'])?$b['period_label']:'',50),':u'=>$mtpcActor['username'],':n'=>text_value(isset($b['note'])?$b['note']:'',500)));$id=$pdo->lastInsertId();mtpc_audit('attendance.session.create','attendance_session',$id,null,array('class_name'=>$class,'subject_name'=>$subject,'session_date'=>$date));mtpc_students_response(201,array('ok'=>true,'id'=>$id,'message'=>'Đã tạo buổi điểm danh.'));
 }
 if($action==='mark_attendance'){
  mtpc_require_permission('attendance.write');$session=id_value(isset($b['session_id'])?$b['session_id']:0);$records=isset($b['records'])&&is_array($b['records'])?$b['records']:array();if(!$session||!count($records))mtpc_students_response(422,array('ok'=>false,'error'=>'Thiếu buổi học hoặc danh sách điểm danh.'));$allowed=array('present','late','excused','absent');$pdo->beginTransaction();$st=$pdo->prepare('INSERT INTO attendance_records(session_id,student_id,status,note,marked_by) VALUES(:session,:student,:status,:note,:actor) ON DUPLICATE KEY UPDATE status=VALUES(status),note=VALUES(note),marked_by=VALUES(marked_by)');foreach($records as$r){$status=isset($r['status'])?(string)$r['status']:'present';if(!in_array($status,$allowed,true))$status='present';$st->execute(array(':session'=>$session,':student'=>id_value(isset($r['student_id'])?$r['student_id']:0),':status'=>$status,':note'=>text_value(isset($r['note'])?$r['note']:'',500),':actor'=>$mtpcActor['username']));}$pdo->commit();mtpc_audit('attendance.mark','attendance_session',$session,null,array('record_count'=>count($records)));mtpc_students_response(200,array('ok'=>true,'message'=>'Đã lưu điểm danh.','count'=>count($records)));
 }
 if($action==='assign_fee'){
  mtpc_require_permission('finance.write');$student=id_value(isset($b['student_id'])?$b['student_id']:0);$name=text_value(isset($b['fee_name'])?$b['fee_name']:'',150);$amount=max(0,(float)(isset($b['amount'])?$b['amount']:0));$discount=max(0,(float)(isset($b['discount_amount'])?$b['discount_amount']:0));if(!$student||$name===''||$amount<=0||$discount>$amount)mtpc_students_response(422,array('ok'=>false,'error'=>'Thông tin khoản thu không hợp lệ.'));$code='FEE-'.date('YmdHis').'-'.substr(md5(uniqid('',true)),0,5);$pdo->beginTransaction();$st=$pdo->prepare('INSERT INTO fee_items(code,name,amount,due_date) VALUES(:c,:n,:a,:d)');$st->execute(array(':c'=>$code,':n'=>$name,':a'=>$amount,':d'=>!empty($b['due_date'])?$b['due_date']:null));$feeItem=$pdo->lastInsertId();$due=$amount-$discount;$st=$pdo->prepare('INSERT INTO student_fees(student_id,fee_item_id,original_amount,discount_amount,discount_reason,amount_due,status,created_by) VALUES(:s,:f,:o,:d,:r,:due,:status,:u)');$st->execute(array(':s'=>$student,':f'=>$feeItem,':o'=>$amount,':d'=>$discount,':r'=>text_value(isset($b['discount_reason'])?$b['discount_reason']:'',500),':due'=>$due,':status'=>$due==0?'waived':'unpaid',':u'=>$mtpcActor['username']));$id=$pdo->lastInsertId();$pdo->commit();mtpc_audit('fee.assign','student_fee',$id,null,array('student_id'=>$student,'amount_due'=>$due));mtpc_students_response(201,array('ok'=>true,'id'=>$id,'message'=>'Đã tạo khoản thu.'));
 }
 if($action==='record_payment'){
  mtpc_require_permission('finance.write');$fee=id_value(isset($b['student_fee_id'])?$b['student_fee_id']:0);$amount=max(0,(float)(isset($b['amount'])?$b['amount']:0));if(!$fee||$amount<=0)mtpc_students_response(422,array('ok'=>false,'error'=>'Khoản thu hoặc số tiền không hợp lệ.'));$st=$pdo->prepare('SELECT sf.amount_due,COALESCE(SUM(p.amount),0) paid FROM student_fees sf LEFT JOIN fee_payments p ON p.student_fee_id=sf.id WHERE sf.id=:id GROUP BY sf.id');$st->execute(array(':id'=>$fee));$row=$st->fetch();if(!$row)mtpc_students_response(404,array('ok'=>false,'error'=>'Không tìm thấy khoản thu.'));$remaining=(float)$row['amount_due']-(float)$row['paid'];if($amount>$remaining)mtpc_students_response(422,array('ok'=>false,'error'=>'Số tiền vượt quá công nợ còn lại.'));$receipt='MTPC-'.date('Ymd-His').'-'.substr(md5(uniqid('',true)),0,4);$pdo->beginTransaction();$st=$pdo->prepare('INSERT INTO fee_payments(student_fee_id,amount,payment_method,reference_code,receipt_no,paid_at,note,received_by) VALUES(:f,:a,:m,:r,:no,NOW(),:n,:u)');$st->execute(array(':f'=>$fee,':a'=>$amount,':m'=>text_value(isset($b['payment_method'])?$b['payment_method']:'Tiền mặt',40),':r'=>text_value(isset($b['reference_code'])?$b['reference_code']:'',100),':no'=>$receipt,':n'=>text_value(isset($b['note'])?$b['note']:'',500),':u'=>$mtpcActor['username']));$status=$amount==$remaining?'paid':'partial';$st=$pdo->prepare('UPDATE student_fees SET status=:s WHERE id=:id');$st->execute(array(':s'=>$status,':id'=>$fee));$pdo->commit();mtpc_audit('fee.payment','student_fee',$fee,null,array('amount'=>$amount,'receipt_no'=>$receipt));mtpc_students_response(201,array('ok'=>true,'receipt_no'=>$receipt,'message'=>'Đã ghi nhận thanh toán.'));
 }
 if($action==='upsert_user'){
  mtpc_require_permission('users.manage');$username=text_value(isset($b['username'])?$b['username']:'',100);$role=text_value(isset($b['role'])?$b['role']:'teacher',20);if($username===''||!in_array($role,array('admin','training','teacher'),true))mtpc_students_response(422,array('ok'=>false,'error'=>'Tài khoản hoặc vai trò không hợp lệ.'));$st=$pdo->prepare("INSERT INTO admin_users(username,full_name,role,status) VALUES(:u,:n,:r,:s) ON DUPLICATE KEY UPDATE full_name=VALUES(full_name),role=VALUES(role),status=VALUES(status)");$st->execute(array(':u'=>$username,':n'=>text_value(isset($b['full_name'])?$b['full_name']:$username,150),':r'=>$role,':s'=>isset($b['status'])&&$b['status']==='disabled'?'disabled':'active'));mtpc_audit('user.upsert','admin_user',$username,null,array('role'=>$role));mtpc_students_response(200,array('ok'=>true,'message'=>'Đã cập nhật phân quyền.'));
 }
 if($action==='upsert_academic'){
  mtpc_require_permission('academic.write');$student=id_value(isset($b['student_id'])?$b['student_id']:0);$semester=id_value(isset($b['semester_id'])?$b['semester_id']:0);$subject=id_value(isset($b['subject_id'])?$b['subject_id']:0);if(!$student||!$semester||!$subject)mtpc_students_response(422,array('ok'=>false,'error'=>'Thiếu sinh viên, học kỳ hoặc môn học.'));$process=isset($b['process_score'])&&$b['process_score']!==''?(float)$b['process_score']:null;$exam=isset($b['exam_score'])&&$b['exam_score']!==''?(float)$b['exam_score']:null;$final=isset($b['final_score'])&&$b['final_score']!==''?(float)$b['final_score']:null;foreach(array($process,$exam,$final) as$score)if($score!==null&&($score<0||$score>10))mtpc_students_response(422,array('ok'=>false,'error'=>'Điểm phải nằm trong khoảng 0–10.'));$result=$final===null?'studying':($final>=5?'passed':'failed');$st=$pdo->prepare('INSERT INTO academic_results(student_id,semester_id,subject_id,process_score,exam_score,final_score,letter_grade,result,updated_by) VALUES(:student,:semester,:subject,:process,:exam,:final,:letter,:result,:actor) ON DUPLICATE KEY UPDATE process_score=VALUES(process_score),exam_score=VALUES(exam_score),final_score=VALUES(final_score),letter_grade=VALUES(letter_grade),result=VALUES(result),updated_by=VALUES(updated_by)');$st->execute(array(':student'=>$student,':semester'=>$semester,':subject'=>$subject,':process'=>$process,':exam'=>$exam,':final'=>$final,':letter'=>text_value(isset($b['letter_grade'])?$b['letter_grade']:'',5),':result'=>$result,':actor'=>$mtpcActor['username']));mtpc_audit('academic.upsert','student',$student,null,array('semester_id'=>$semester,'subject_id'=>$subject,'final_score'=>$final));mtpc_students_response(200,array('ok'=>true,'message'=>'Đã cập nhật kết quả học tập.'));
 }
 if($action==='create_student_action'){
  mtpc_require_permission('students.write');$student=id_value(isset($b['student_id'])?$b['student_id']:0);$type=text_value(isset($b['action_type'])?$b['action_type']:'',20);$allowed=array('reward','discipline','reserve','withdraw','return');$date=text_value(isset($b['effective_date'])?$b['effective_date']:'',10);$reason=text_value(isset($b['reason'])?$b['reason']:'',1000);if(!$student||!in_array($type,$allowed,true)||$reason===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))mtpc_students_response(422,array('ok'=>false,'error'=>'Thông tin quyết định chưa hợp lệ.'));$st=$pdo->prepare('INSERT INTO student_actions(student_id,action_type,decision_no,effective_date,end_date,reason,status,created_by) VALUES(:student,:type,:decision,:effective,:end,:reason,:status,:actor)');$st->execute(array(':student'=>$student,':type'=>$type,':decision'=>text_value(isset($b['decision_no'])?$b['decision_no']:'',80),':effective'=>$date,':end'=>!empty($b['end_date'])?$b['end_date']:null,':reason'=>$reason,':status'=>isset($b['status'])&&in_array($b['status'],array('draft','active','completed','cancelled'),true)?$b['status']:'draft',':actor'=>$mtpcActor['username']));$id=$pdo->lastInsertId();mtpc_audit('student.action.create','student_action',$id,null,array('student_id'=>$student,'action_type'=>$type));mtpc_students_response(201,array('ok'=>true,'id'=>$id,'message'=>'Đã lưu quyết định sinh viên.'));
 }
 if($action==='add_document'){
  mtpc_require_permission('students.write');$student=id_value(isset($b['student_id'])?$b['student_id']:0);$type=text_value(isset($b['document_type'])?$b['document_type']:'',80);$name=text_value(isset($b['file_name'])?$b['file_name']:'',255);$path=text_value(isset($b['file_path'])?$b['file_path']:'',500);if(!$student||$type===''||$name===''||$path==='')mtpc_students_response(422,array('ok'=>false,'error'=>'Thiếu thông tin giấy tờ.'));$st=$pdo->prepare('INSERT INTO student_documents(student_id,document_type,file_name,file_path,status,note,uploaded_by) VALUES(:student,:type,:name,:path,:status,:note,:actor)');$st->execute(array(':student'=>$student,':type'=>$type,':name'=>$name,':path'=>$path,':status'=>'pending',':note'=>text_value(isset($b['note'])?$b['note']:'',500),':actor'=>$mtpcActor['username']));mtpc_audit('student.document.add','student',$student,null,array('document_type'=>$type,'file_name'=>$name));mtpc_students_response(201,array('ok'=>true,'message'=>'Đã ghi nhận giấy tờ.'));
 }
 if($action==='restore_backup'){
  mtpc_require_permission('backup.manage');if(!isset($b['confirm'])||$b['confirm']!=='RESTORE'||!isset($b['backup']['tables'])||!is_array($b['backup']['tables']))mtpc_students_response(422,array('ok'=>false,'error'=>'File sao lưu hoặc mã xác nhận không hợp lệ.'));$allowed=array('students','student_history','semesters','subjects','academic_results','attendance_sessions','attendance_records','fee_items','student_fees','fee_payments','student_actions');$pdo->beginTransaction();$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(array_reverse($allowed)as$t)$pdo->exec('DELETE FROM `'.$t.'`');foreach($allowed as$t){$rows=isset($b['backup']['tables'][$t])&&is_array($b['backup']['tables'][$t])?$b['backup']['tables'][$t]:array();$columns=array();foreach($pdo->query('DESCRIBE `'.$t.'')->fetchAll()as$col)$columns[]=$col['Field'];foreach($rows as$row){$use=array();foreach($columns as$c)if(array_key_exists($c,$row))$use[$c]=$row[$c];if(!count($use))continue;$names=array_keys($use);$marks=array();$params=array();foreach($names as$c){$marks[]=':'.$c;$params[':'.$c]=$use[$c];}$st=$pdo->prepare('INSERT INTO `'.$t.'` (`'.implode('`,`',$names).'`) VALUES ('.implode(',',$marks).')');$st->execute($params);}}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');$pdo->commit();mtpc_audit('backup.restore','system','student-management',null,array('version'=>isset($b['backup']['version'])?$b['backup']['version']:null));mtpc_students_response(200,array('ok'=>true,'message'=>'Đã khôi phục dữ liệu từ bản sao lưu.'));
 }
 if($action==='import_students'){
  mtpc_require_permission('students.write');$rows=isset($b['rows'])&&is_array($b['rows'])?$b['rows']:array();if(!count($rows)||count($rows)>500)mtpc_students_response(422,array('ok'=>false,'error'=>'File nhập cần từ 1 đến 500 dòng.'));$inserted=0;$updated=0;$errors=array();$pdo->beginTransaction();foreach($rows as$i=>$r){$code=text_value(isset($r['student_code'])?$r['student_code']:'',30);$name=text_value(isset($r['full_name'])?$r['full_name']:'',150);if($code===''||$name===''){$errors[]=array('row'=>$i+2,'error'=>'Thiếu mã hoặc họ tên');continue;}try{$st=$pdo->prepare('SELECT id FROM students WHERE student_code=:c LIMIT 1');$st->execute(array(':c'=>$code));$id=$st->fetchColumn();$data=array(':c'=>$code,':n'=>$name,':dob'=>!empty($r['date_of_birth'])?$r['date_of_birth']:null,':p'=>text_value(isset($r['phone'])?$r['phone']:'',30),':e'=>text_value(isset($r['email'])?$r['email']:'',150),':program'=>text_value(isset($r['program_name'])?$r['program_name']:'',150),':class'=>text_value(isset($r['class_name'])?$r['class_name']:'',100),':status'=>text_value(isset($r['status'])?$r['status']:'Đang học',50));if($id){$data[':id']=$id;$st=$pdo->prepare('UPDATE students SET full_name=:n,date_of_birth=:dob,phone=:p,email=:e,program_name=:program,class_name=:class,status=:status WHERE id=:id');$st->execute($data);$updated++;}else{$st=$pdo->prepare('INSERT INTO students(student_code,full_name,date_of_birth,phone,email,program_name,class_name,status) VALUES(:c,:n,:dob,:p,:e,:program,:class,:status)');$st->execute($data);$inserted++;}}catch(Exception$e){$errors[]=array('row'=>$i+2,'error'=>'Trùng CCCD, email, số điện thoại hoặc dữ liệu sai');}}$pdo->commit();mtpc_audit('students.import','student','bulk',null,array('inserted'=>$inserted,'updated'=>$updated,'errors'=>count($errors)));mtpc_students_response(200,array('ok'=>true,'inserted'=>$inserted,'updated'=>$updated,'errors'=>$errors,'message'=>'Đã hoàn tất nhập dữ liệu.'));
 }
 mtpc_students_response(400,array('ok'=>false,'error'=>'Thao tác không hợp lệ.'));
}catch(PDOException$e){if($pdo->inTransaction())$pdo->rollBack();mtpc_students_response(500,array('ok'=>false,'error'=>'Database không thể xử lý yêu cầu.'));}catch(Exception$e){if($pdo->inTransaction())$pdo->rollBack();mtpc_students_response(500,array('ok'=>false,'error'=>'Không thể xử lý yêu cầu.'));}
